version: '2' 
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    platform: linux/amd64
    volumes:
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources/hadoop:/opt/hadoop/resources
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources:/opt/resources
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 9010:9000
  
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    platform: linux/amd64
    container_name: datanode1
    depends_on: 
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - "9864:9864"
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.8-java8
    container_name: resourcemanager
    platform: linux/amd64
    restart: always
    ports:
      - 8031:8031
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.8-java8
    container_name: nodemanager
    platform: linux/amd64
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8031"
    env_file:
      - ./hadoop.env
  
  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    volumes:
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources/hadoop:/opt/hadoop/resources
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources:/opt/resources
    container_name: hive-server
    env_file:
      - ./hadoop.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"
  
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
  
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    platform: linux/amd64
  
  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    platform: linux/amd64
    volumes:
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources/hadoop:/opt/hadoop/resources
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources:/opt/resources
    depends_on:
      - namenode
      - datanode
      - hive-server
      - hive-metastore
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
  
  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
    platform: linux/amd64
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop.env
  
  spark-notebook:
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    platform: linux/amd64
    container_name: spark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
      - hive-server

  zeppelin-notebook:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    platform: linux/amd64
    restart: always
    ports:
      - 8089:8080
    volumes:
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources/hadoop:/opt/hadoop/resources
      - /Users/shehantharuka/Workspace/Programming/MSc-Dev/coursework/big-data-programming/resources:/opt/resources